loaders:
  - modules:
      - haystack_integrations.components.generators.aimlapi.chat.chat_generator
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: AIMLAPI integration for Haystack
  id: integrations-aimlapi
  filename: aimlapi.md
  title: AIMLAPI
