loaders:
  - modules:
      - haystack_integrations.components.converters.unstructured.converter
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Unstructured integration for Haystack
  id: integrations-unstructured
  filename: unstructured.md
  title: Unstructured
