loaders:
  - modules:
      - haystack_integrations.components.evaluators.ragas.evaluator
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Ragas integration for Haystack
  id: integrations-ragas
  filename: ragas.md
  title: Ragas
