loaders:
- ignore_when_discovered:
  - __init__
  modules:
  - haystack_integrations.components.connectors.weave.weave_connector
  - haystack_integrations.tracing.weave.tracer
  search_path:
  - ../src
  type: haystack_pydoc_tools.loaders.CustomPythonLoader
processors:
- do_not_filter_modules: false
  documented_only: true
  expression: null
  skip_empty_modules: true
  type: filter
- type: smart
- type: crossref
renderer:
  description: Weights & Bias integration for Haystack
  id: integrations-weights-bias
  markdown:
    add_member_class_prefix: false
    add_method_class_prefix: true
    classdef_code_block: false
    descriptive_class_title: false
    descriptive_module_title: true
    filename: weights_and_bias.md
  title: weights and bias
  type: haystack_pydoc_tools.renderers.DocusaurusRenderer
