loaders:
  - modules:
      - haystack_integrations.components.connectors.langfuse.langfuse_connector
      - haystack_integrations.tracing.langfuse.tracer
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Langfuse integration for Haystack
  id: integrations-langfuse
  filename: langfuse.md
  title: langfuse
