loaders:
  - modules:
      - haystack_integrations.components.generators.google_ai.gemini
      - haystack_integrations.components.generators.google_ai.chat.gemini
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Google AI integration for Haystack
  id: integrations-google-ai
  filename: google_ai.md
  title: Google AI
