loaders:
  - modules:
      - haystack_integrations.document_stores.weaviate.auth
      - haystack_integrations.document_stores.weaviate.document_store
      - haystack_integrations.components.retrievers.weaviate.bm25_retriever
      - haystack_integrations.components.retrievers.weaviate.embedding_retriever
      - haystack_integrations.components.retrievers.weaviate.hybrid_retriever
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Weaviate integration for Haystack
  id: integrations-weaviate
  filename: weaviate.md
  title: Weaviate
