loaders:
  - modules:
      - haystack_integrations.components.embedders.jina.document_embedder
      - haystack_integrations.components.embedders.jina.document_image_embedder
      - haystack_integrations.components.embedders.jina.text_embedder
      - haystack_integrations.components.rankers.jina.ranker
      - haystack_integrations.components.connectors.jina.reader
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Jina integration for Haystack
  id: integrations-jina
  filename: jina.md
  title: Jina
