loaders:
  - modules:
      - haystack_integrations.components.generators.anthropic.generator
      - haystack_integrations.components.generators.anthropic.chat.chat_generator
      - haystack_integrations.components.generators.anthropic.chat.vertex_chat_generator
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Anthropic integration for Haystack
  id: integrations-anthropic
  filename: anthropic.md
  title: Anthropic
