loaders:
  - modules:
      - haystack_integrations.components.generators.amazon_sagemaker.sagemaker
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Amazon Sagemaker integration for Haystack
  id: integrations-amazon-sagemaker
  filename: amazon_sagemaker.md
  title: Amazon Sagemaker
