loaders:
  - modules:
      - haystack_integrations.components.generators.stackit.chat.chat_generator
      - haystack_integrations.components.embedders.stackit.document_embedder
      - haystack_integrations.components.embedders.stackit.text_embedder
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: STACKIT integration for Haystack
  id: integrations-stackit
  filename: stackit.md
  title: STACKIT
