loaders:
  - modules:
      - haystack_integrations.components.retrievers.astra.retriever
      - haystack_integrations.document_stores.astra.document_store
      - haystack_integrations.document_stores.astra.errors
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Astra integration for Haystack
  id: integrations-astra
  filename: astra.md
  title: Astra
