loaders:
  - modules:
      - haystack_integrations.components.generators.togetherai.generator
      - haystack_integrations.components.generators.togetherai.chat.chat_generator
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Together AI integration for Haystack
  id: integrations-togetherai
  filename: togetherai.md
  title: Together AI
