loaders:
  - modules:
      - haystack_integrations.components.embedders.mistral.document_embedder
      - haystack_integrations.components.embedders.mistral.text_embedder
      - haystack_integrations.components.generators.mistral.chat.chat_generator
      - haystack_integrations.components.converters.mistral.ocr_document_converter
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Mistral integration for Haystack
  id: integrations-mistral
  filename: mistral.md
  title: Mistral
