loaders:
  - modules:
      - haystack_integrations.components.retrievers.chroma.retriever
      - haystack_integrations.document_stores.chroma.document_store
      - haystack_integrations.document_stores.chroma.errors
      - haystack_integrations.document_stores.chroma.utils
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Chroma integration for Haystack
  id: integrations-chroma
  filename: chroma.md
  title: Chroma
