loaders:
  - modules:
      - haystack_integrations.components.retrievers.snowflake.snowflake_table_retriever
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Snowflake integration for Haystack
  id: integrations-snowflake
  filename: snowflake.md
  title: Snowflake
