loaders:
  - modules:
      - haystack_integrations.components.generators.ollama.generator
      - haystack_integrations.components.generators.ollama.chat.chat_generator
      - haystack_integrations.components.embedders.ollama.document_embedder
      - haystack_integrations.components.embedders.ollama.text_embedder
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Ollama integration for Haystack
  id: integrations-ollama
  filename: ollama.md
  title: Ollama
