loaders:
  - modules:
      - haystack_integrations.components.preprocessors.hanlp.chinese_document_splitter
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: HanLP integration for Haystack
  id: integrations-hanlp
  filename: hanlp.md
  title: HanLP
