loaders:
  - modules:
      - haystack_integrations.tools.mcp.mcp_tool
      - haystack_integrations.tools.mcp.mcp_toolset
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: MCP integration for Haystack
  id: integrations-mcp
  filename: mcp.md
  title: MCP
