loaders:
  - modules:
      - haystack_integrations.components.generators.google_vertex.gemini
      - haystack_integrations.components.generators.google_vertex.captioner
      - haystack_integrations.components.generators.google_vertex.code_generator
      - haystack_integrations.components.generators.google_vertex.image_generator
      - haystack_integrations.components.generators.google_vertex.question_answering
      - haystack_integrations.components.generators.google_vertex.text_generator
      - haystack_integrations.components.generators.google_vertex.chat.gemini
      - haystack_integrations.components.embedders.google_vertex.document_embedder
      - haystack_integrations.components.embedders.google_vertex.text_embedder
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Google Vertex integration for Haystack
  id: integrations-google-vertex
  filename: google_vertex.md
  title: Google Vertex
