loaders:
  - modules:
      - haystack_integrations.components.generators.cometapi.chat.chat_generator
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Comet API integration for Haystack
  id: integrations-cometapi
  filename: cometapi.md
  title: Comet API
