loaders:
  - type: haystack_pydoc_tools.loaders.CustomPythonLoader
    search_path: [../src]
    modules:
      [
        "haystack_integrations.components.embedders.optimum_backend",
        "haystack_integrations.components.embedders.optimum_document_embedder",
        "haystack_integrations.components.embedders.optimum_text_embedder",
        "haystack_integrations.components.embedders.pooling",
      ]
    ignore_when_discovered: ["__init__"]
processors:
  - type: filter
    expression:
    documented_only: true
    do_not_filter_modules: false
    skip_empty_modules: true
  - type: smart
  - type: crossref
renderer:
  type: haystack_pydoc_tools.renderers.ReadmePreviewRenderer
  excerpt: Optimum integration for Haystack
  category_slug: haystack-integrations
  title: Optimum
  slug: integrations-optimum
  order: 190
  markdown:
    descriptive_class_title: false
    descriptive_module_title: true
    add_method_class_prefix: true
    add_member_class_prefix: false
    filename: _readme_optimum.md
