loaders:
  - modules:
      - haystack_integrations.components.embedders.optimum.optimum_document_embedder
      - haystack_integrations.components.embedders.optimum.optimum_text_embedder
      - haystack_integrations.components.embedders.optimum.pooling
      - haystack_integrations.components.embedders.optimum.optimization
      - haystack_integrations.components.embedders.optimum.quantization
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Optimum integration for Haystack
  id: integrations-optimum
  filename: optimum.md
  title: Optimum
