loaders:
  - modules:
      - haystack_integrations.components.generators.meta_llama.chat.chat_generator
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Meta Llama API integration for Haystack
  id: integrations-meta-llama
  filename: meta_llama.md
  title: Meta Llama API
