loaders:
  - modules:
      - haystack_integrations.components.retrievers.opensearch.bm25_retriever
      - haystack_integrations.components.retrievers.opensearch.embedding_retriever
      - haystack_integrations.components.retrievers.opensearch.metadata_retriever
      - haystack_integrations.components.retrievers.opensearch.open_search_hybrid_retriever
      - haystack_integrations.components.retrievers.opensearch.sql_retriever
      - haystack_integrations.document_stores.opensearch.document_store
      - haystack_integrations.document_stores.opensearch.filters
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: OpenSearch integration for Haystack
  id: integrations-opensearch
  filename: opensearch.md
  title: OpenSearch
