# SPDX-FileCopyrightText: 2022-present deepset GmbH <info@deepset.ai>
#
# SPDX-License-Identifier: Apache-2.0
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "haystack-speech2text"
description = 'Haystack node to convert audio files into Documents.'
readme = "README.md"
requires-python = ">=3.7"
license = "Apache-2.0"
keywords = []
authors = [
  { name = "deepset GmbH", email = "info@deepset.ai" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "farm-haystack",
  "numpy",
  "torch",
  "pydantic",
  "torchaudio",
]

dynamic = ["version"]

[project.optional-dependencies]
whisper = [
  "whisper@git+https://github.com/openai/whisper.git"
]
wav2vec = [
  "transformers",
  "librosa",
  "pydub",
  "tqdm"
]
aeneas = [
  "aeneas"
]

dev = [
  "pre-commit",
  "mypy",
  "typing_extensions; python_version < '3.8'",
  "pytest",
  "tox",
  "coverage",
  "pylint",
  "black[jupyter]==22.8.0",
  "pydoc-markdown",
  "mkdocs",
  "jupytercontrib",
]

[project.urls]
Documentation = "https://github.com/deepset-ai/haystack-extras/tree/main/nodes/speech2text#readme"
Issues = "https://github.com/deepset-ai/haystack-extras/issues"
Source = "https://github.com/deepset-ai/haystack-extras/tree/main/nodes/speech2text"

[tool.hatch.version]
path = "speech2text/__about__.py"

[tool.hatch.envs.default]
dependencies = [
  "pytest",
  "pytest-cov",
]
[tool.hatch.envs.default.scripts]
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=speech2text --cov=tests"
no-cov = "cov --no-cov"

[tool.hatch.metadata]
allow-direct-references = true

[[tool.hatch.envs.test.matrix]]
python = ["37", "38", "39", "310", "311"]

[tool.coverage.run]
branch = true
parallel = true
omit = [
  "speech2text/__about__.py",
]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.pylint.'MESSAGES CONTROL']
max-line-length=120
disable = [
  "missing-module-docstring",
  "fixme"
]
[tool.pylint.'DESIGN']
max-args=7
[tool.pylint.'SIMILARITIES']
min-similarity-lines=6

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--strict-markers"
markers = [
  "integration: integration tests",
  "unit: unit tests",
]
log_cli = true

[tool.black]
line-length = 120
