loaders:
  - modules:
      - haystack_integrations.components.retrievers.elasticsearch.bm25_retriever
      - haystack_integrations.components.retrievers.elasticsearch.embedding_retriever
      - haystack_integrations.components.retrievers.elasticsearch.sql_retriever
      - haystack_integrations.document_stores.elasticsearch.document_store
      - haystack_integrations.document_stores.elasticsearch.filters
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Elasticsearch integration for Haystack
  id: integrations-elasticsearch
  filename: elasticsearch.md
  title: Elasticsearch
