loaders:
  - modules:
      - haystack_integrations.components.retrievers.pinecone.embedding_retriever
      - haystack_integrations.document_stores.pinecone.document_store
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Pinecone integration for Haystack
  id: integrations-pinecone
  filename: pinecone.md
  title: Pinecone
