loaders:
  - type: haystack_pydoc_tools.loaders.CustomPythonLoader
    search_path: [../src]
    modules:
      [
        "haystack_integrations.components.retrievers.pinecone.dense_retriever",
        "haystack_integrations.document_stores.pinecone.document_store",
        "haystack_integrations.document_stores.pinecone.errors",
        "haystack_integrations.document_stores.pinecone.filters",
      ]
    ignore_when_discovered: ["__init__"]
processors:
  - type: filter
    expression:
    documented_only: true
    do_not_filter_modules: false
    skip_empty_modules: true
  - type: smart
  - type: crossref
renderer:
  type: haystack_pydoc_tools.renderers.ReadmePreviewRenderer
  excerpt: Pinecone integration for Haystack
  category_slug: haystack-integrations
  title: Pinecone
  slug: integrations-pinecone
  order: 150
  markdown:
    descriptive_class_title: false
    descriptive_module_title: true
    add_method_class_prefix: true
    add_member_class_prefix: false
    filename: _readme_pinecone.md
