loaders:
  - modules:
      - haystack_integrations.components.generators.llama_stack.chat.chat_generator
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Llama Stack integration for Haystack
  id: integrations-llama-stack
  filename: llama_stack.md
  title: Llama Stack
