loaders:
  - modules:
      - haystack_integrations.components.embedders.fastembed.fastembed_document_embedder
      - haystack_integrations.components.embedders.fastembed.fastembed_text_embedder
      - haystack_integrations.components.embedders.fastembed.fastembed_sparse_document_embedder
      - haystack_integrations.components.embedders.fastembed.fastembed_sparse_text_embedder
      - haystack_integrations.components.rankers.fastembed.ranker
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: FastEmbed integration for Haystack
  id: fastembed-embedders
  filename: fastembed.md
  title: FastEmbed
