loaders:
  - modules:
      - haystack_integrations.components.connectors.github.file_editor
      - haystack_integrations.components.connectors.github.issue_commenter
      - haystack_integrations.components.connectors.github.issue_viewer
      - haystack_integrations.components.connectors.github.pr_creator
      - haystack_integrations.components.connectors.github.repo_viewer
      - haystack_integrations.components.connectors.github.repo_forker
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: GitHub integration for Haystack
  id: integrations-github
  filename: github.md
  title: GitHub
