loaders:
  - modules:
      - haystack_integrations.components.connectors.weave.weave_connector
      - haystack_integrations.tracing.weave.tracer
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Weights & Bias integration for Haystack
  id: integrations-weave
  filename: weave.md
  title: Weave
