loaders:
  - modules:
      - haystack_integrations.components.embedders.cohere.document_embedder
      - haystack_integrations.components.embedders.cohere.document_image_embedder
      - haystack_integrations.components.embedders.cohere.text_embedder
      - haystack_integrations.components.embedders.cohere.utils
      - haystack_integrations.components.generators.cohere.generator
      - haystack_integrations.components.generators.cohere.chat.chat_generator
      - haystack_integrations.components.rankers.cohere.ranker
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Cohere integration for Haystack
  id: integrations-cohere
  filename: cohere.md
  title: Cohere
