loaders:
  - type: haystack_pydoc_tools.loaders.CustomPythonLoader
    search_path: [../src]
    modules: [
      "haystack_integrations.components.generators.amazon_bedrock.generator",
      "haystack_integrations.components.generators.amazon_bedrock.adapters",
      "haystack_integrations.common.amazon_bedrock.errors",
      "haystack_integrations.components.generators.amazon_bedrock.handlers",
      "haystack_integrations.components.generators.amazon_bedrock.chat.chat_generator",
      "haystack_integrations.components.embedders.amazon_bedrock.text_embedder",
      "haystack_integrations.components.embedders.amazon_bedrock.document_embedder",
    ]
    ignore_when_discovered: ["__init__"]
processors:
  - type: filter
    expression:
    documented_only: true
    do_not_filter_modules: false
    skip_empty_modules: true
  - type: smart
  - type: crossref
renderer:
  type: haystack_pydoc_tools.renderers.ReadmeIntegrationRenderer
  excerpt: Amazon Bedrock integration for Haystack
  category_slug: integrations-api
  title: Amazon Bedrock
  slug: integrations-amazon-bedrock
  order: 9
  markdown:
    descriptive_class_title: false
    classdef_code_block: false
    descriptive_module_title: true
    add_method_class_prefix: true
    add_member_class_prefix: false
    filename: _readme_amazon_bedrock.md
