loaders:
  - modules:
      - haystack_integrations.components.generators.watsonx.generator
      - haystack_integrations.components.generators.watsonx.chat.chat_generator
      - haystack_integrations.components.embedders.watsonx.document_embedder
      - haystack_integrations.components.embedders.watsonx.text_embedder
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: IBM watsonx.ai integration for Haystack
  id: integrations-watsonx
  filename: watsonx.md
  title: IBM watsonx.ai
