loaders:
  - modules:
      - haystack_integrations.components.embedders.nvidia.document_embedder
      - haystack_integrations.components.embedders.nvidia.text_embedder
      - haystack_integrations.components.embedders.nvidia.truncate
      - haystack_integrations.components.generators.nvidia.generator
      - haystack_integrations.components.generators.nvidia.chat.chat_generator
      - haystack_integrations.components.rankers.nvidia.ranker
      - haystack_integrations.components.rankers.nvidia.truncate
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Nvidia integration for Haystack
  id: integrations-nvidia
  filename: nvidia.md
  title: Nvidia
