loaders:
- ignore_when_discovered:
  - __init__
  modules:
  - haystack_integrations.components.embedders.nvidia.document_embedder
  - haystack_integrations.components.embedders.nvidia.text_embedder
  - haystack_integrations.components.embedders.nvidia.truncate
  - haystack_integrations.components.generators.nvidia.generator
  - haystack_integrations.components.generators.nvidia.chat.chat_generator
  - haystack_integrations.components.rankers.nvidia.ranker
  - haystack_integrations.components.rankers.nvidia.truncate
  search_path:
  - ../src
  type: haystack_pydoc_tools.loaders.CustomPythonLoader
processors:
- do_not_filter_modules: false
  documented_only: true
  expression: null
  skip_empty_modules: true
  type: filter
- type: smart
- type: crossref
renderer:
  description: Nvidia integration for Haystack
  id: integrations-nvidia
  markdown:
    add_member_class_prefix: false
    add_method_class_prefix: true
    classdef_code_block: false
    descriptive_class_title: false
    descriptive_module_title: true
    filename: nvidia.md
  title: Nvidia
  type: haystack_pydoc_tools.renderers.DocusaurusRenderer
