loaders:
  - modules:
      - haystack_integrations.components.generators.openrouter.chat.chat_generator
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: OpenRouter integration for Haystack
  id: integrations-openrouter
  filename: openrouter.md
  title: OpenRouter
