loaders:
  - modules:
      - haystack_integrations.components.generators.google_genai.chat.chat_generator
      - haystack_integrations.components.embedders.google_genai.document_embedder
      - haystack_integrations.components.embedders.google_genai.text_embedder
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Google GenAI integration for Haystack
  id: integrations-google-genai
  filename: google_genai.md
  title: Google GenAI
