loaders:
  - modules:
      - haystack_integrations.components.generators.llama_cpp.generator
      - haystack_integrations.components.generators.llama_cpp.chat.chat_generator
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Llama.cpp integration for Haystack
  id: integrations-llama-cpp
  filename: llama_cpp.md
  title: Llama.cpp
