loaders:
  - modules:
      - haystack_integrations.components.retrievers.qdrant.retriever
      - haystack_integrations.document_stores.qdrant.document_store
      - haystack_integrations.document_stores.qdrant.migrate_to_sparse
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Qdrant integration for Haystack
  id: integrations-qdrant
  filename: qdrant.md
  title: Qdrant
