loaders:
  - modules:
      - haystack_integrations.components.retrievers.azure_ai_search.embedding_retriever
      - haystack_integrations.document_stores.azure_ai_search.document_store
      - haystack_integrations.document_stores.azure_ai_search.filters
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Azure AI Search integration for Haystack
  id: integrations-azure_ai_search
  filename: azure_ai_search.md
  title: Azure AI Search
