loaders:
  - modules:
      - haystack_integrations.components.evaluators.deepeval.evaluator
      - haystack_integrations.components.evaluators.deepeval.metrics
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: DeepEval integration for Haystack
  id: integrations-deepeval
  filename: deepeval.md
  title: DeepEval
