loaders:
  - modules:
      - haystack_integrations.document_stores.mongodb_atlas.document_store
      - haystack_integrations.document_stores.mongodb_atlas.filters
      - haystack_integrations.components.retrievers.mongodb_atlas.embedding_retriever
      - haystack_integrations.components.retrievers.mongodb_atlas.full_text_retriever
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: MongoDB Atlas integration for Haystack
  id: integrations-mongodb-atlas
  filename: mongodb_atlas.md
  title: MongoDB Atlas
