name: Test / text2speech

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'nodes/text2speech/**'
      - '.github/workflows/nodes_text2speech.yml'

defaults:
  run:
    working-directory: nodes/text2speech

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install audio libraries
      run: |
        sudo apt-get update
        sudo apt-get install libsndfile1 ffmpeg

    - name: Install text2speech
      run: |
        pip install -e .[dev]

    - name: Pylint
      run: |
        pylint -ry -j 0 ./text2speech

    - name: Run tests
      run: |
        pytest