loaders:
  - modules:
      - haystack_integrations.components.retrievers.pgvector.embedding_retriever
      - haystack_integrations.components.retrievers.pgvector.keyword_retriever
      - haystack_integrations.document_stores.pgvector.document_store
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Pgvector integration for Haystack
  id: integrations-pgvector
  filename: pgvector.md
  title: Pgvector
